// Export all section components for easy importing
export { default as Navbar } from './Navbar';
export { default as HeroSection } from './HeroSection';
export { default as OurServices } from './OurServices';
export { default as HowWeWork } from './HowWeWork';
export { default as ImpactFocus } from './ImpactFocus';
export { default as TransformingHealthcare } from './TransformingHealthcare';
export { default as PartnerExcellence } from './PartnerExcellence';
export { default as Footer } from './Footer';
